
# Copyright (C) 2006 Junjiro Okajima
# Copyright (C) 2006 Tomas Matejicek, slax.org

# LICENSE follows the described one in lzma.txt.

# $Id: Makefile,v 1.3 2006/11/27 03:54:58 jro Exp $

#
# Makefile for the linux squashfs routines.
#

obj-$(CONFIG_SQUASHFS) += unlzma.o sqlzma.o squashfs.o
unlzma-y += module.o
sqlzma-y += uncomp.o
squashfs-y += inode.o
squashfs-y += squashfs2_0.o
